name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build

    - name: Start server
      run: |
        npm run start &
        sleep 20  # Increased wait time to ensure the server has time to start
        curl -s http://localhost:8080/ping || echo "Server did not start successfully"

  
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run start
